config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :users
resource :session, only: [:create, :new, :destroy]
resources :bands
resources :albums
end

app/models/album.rb
class Album < ApplicationRecord
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true


  
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
  end

  def create
    @band = Band.new(band_params)
    if @band.save
    end
  end

  def new
    @band = Band.new
  end

  def edit
  end

  def show
    @band = Band.find(params[:id])
  end

  def update
  end

  def destroy
  end

  private

  def user_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = 'Did not work'
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user.id)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <header>
    Music App
  </header>
    <head>
      <title>MusicApp</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

  <body>
    <%= yield %>
  </body>

  <% if logged_in? %>
  <h2> <%= current_user.email %>
    </h2>
    <form action="<%=session_url%>" method="get">
    <input type="submit" name="" value="Logout">
    <a href="<%=session_url%>"> Logout (doesnt work yet ;))</a>
  </form>
  <% else %>
     <a href="<%=new_user_url%>"> Sign Up</a>
     <a href=" <%= new_session_url %> ">Login</a>
  <% end %>

</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%=users_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <input type="text" name="user[email]" value="">
  <input type="password" name="user[password]" value="">
  <input type="submit" name="" value="Sign Up!">
</form>

app/views/users/show.html.erb
<h1>User's Email is <%= @user.email %> </h1>